/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cover.java
 *
 * Created on Jan 5, 2016, 10:53:57 AM
 */

package hospitalmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Chandrika
 */
public class Cover extends javax.swing.JFrame {


    /** Creates new form Cover */
    public Cover() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        insp = new javax.swing.JButton();
        delp = new javax.swing.JButton();
        modp = new javax.swing.JButton();
        viewp = new javax.swing.JButton();
        srch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Patients List");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        insp.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        insp.setForeground(new java.awt.Color(0, 0, 255));
        insp.setText("Insert New Patient");
        insp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inspActionPerformed(evt);
            }
        });

        delp.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        delp.setForeground(new java.awt.Color(0, 0, 255));
        delp.setText("Delete Patient");
        delp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delpActionPerformed(evt);
            }
        });

        modp.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        modp.setForeground(new java.awt.Color(0, 0, 255));
        modp.setText("Modify Patient Detail");
        modp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modpActionPerformed(evt);
            }
        });

        viewp.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        viewp.setForeground(new java.awt.Color(0, 0, 255));
        viewp.setText("View Patients List");
        viewp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpActionPerformed(evt);
            }
        });

        srch.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        srch.setForeground(new java.awt.Color(0, 0, 255));
        srch.setText("Search For Patient");
        srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Enter Operation :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srch, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(modp, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewp, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delp, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(insp, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insp)
                .addGap(18, 18, 18)
                .addComponent(delp)
                .addGap(18, 18, 18)
                .addComponent(modp)
                .addGap(18, 18, 18)
                .addComponent(viewp)
                .addGap(18, 18, 18)
                .addComponent(srch)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void inspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inspActionPerformed
        Ins in = new Ins();
        in.setVisible(true);
        in.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_inspActionPerformed

    private void delpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delpActionPerformed
        Del d = new Del();
        d.setVisible(true);
        d.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_delpActionPerformed

    private void modpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modpActionPerformed
        Mod m = new Mod();
        m.setVisible(true);
        m.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_modpActionPerformed

    private void viewpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpActionPerformed
       ViewList v = new ViewList();
       v.setVisible(true);
       v.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_viewpActionPerformed

    private void srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchActionPerformed
        srch s = new srch();
        s.setVisible(true);
        s.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_srchActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cover().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delp;
    private javax.swing.JButton insp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modp;
    private javax.swing.JButton srch;
    private javax.swing.JButton viewp;
    // End of variables declaration//GEN-END:variables

}
