/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ins.java
 *
 * Created on Jan 5, 2016, 10:54:10 AM
 */

package hospitalmanagement;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Chandrika
 */
public class Ins extends javax.swing.JFrame {

    /** Creates new form Ins */
    public Ins() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reg = new javax.swing.JTextField();
        nam = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        room = new javax.swing.JTextField();
        bed = new javax.swing.JTextField();
        gur = new javax.swing.JTextField();
        insVar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insert New Patient");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 252, -1));
        jPanel1.add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 252, -1));
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 252, -1));
        jPanel1.add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 252, -1));
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 250, -1));

        room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomActionPerformed(evt);
            }
        });
        jPanel1.add(room, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 252, -1));
        jPanel1.add(bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 252, -1));
        jPanel1.add(gur, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 252, -1));

        insVar.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        insVar.setForeground(new java.awt.Color(0, 102, 0));
        insVar.setText("Insert");
        insVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insVarActionPerformed(evt);
            }
        });
        jPanel1.add(insVar, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 345, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Registration Number :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Age :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Gender :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("Room Number :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("Bed Number :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setText("Gurdian Name :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("Contact Number :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomActionPerformed

    private void insVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insVarActionPerformed
        Connection conn = null;
        PreparedStatement pstmt = null;
        String regi = String.valueOf(reg.getText());
        String name = nam.getText();
        String agee = String.valueOf(age.getText());
        String genn = gen.getText();
        String roomm = String.valueOf(room.getText());
        String bedd = String.valueOf(bed.getText());
        String grud = gur.getText();
        String cont = contact.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","test123");
            pstmt = (PreparedStatement) conn.prepareStatement("insert into patient values(?,?,?,?,?,?,?,?)");
            pstmt.setString(1,regi);
            pstmt.setString(2,name);
            pstmt.setString(3,agee);
            pstmt.setString(4,genn);
            pstmt.setString(5,roomm);
            pstmt.setString(6,bedd);
            pstmt.setString(7,grud);
            pstmt.setString(8,cont);

            int i = pstmt.executeUpdate();
            if(i>0){
                this.dispose();
                JOptionPane.showMessageDialog(null, "Data is Inserted..!!");
                
            }
            else{
                this.dispose();
                JOptionPane.showMessageDialog(null, "Data not Inserted..!!");
            }
        }
        catch(Exception e){
            this.dispose();
            JOptionPane.showMessageDialog(null, "Data not Inserted..!!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_insVarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField bed;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField gen;
    private javax.swing.JTextField gur;
    private javax.swing.JButton insVar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nam;
    private javax.swing.JTextField reg;
    private javax.swing.JTextField room;
    // End of variables declaration//GEN-END:variables

}
